name: Backend Deploy to Render

on:
    push: 
        branches: [ master ]
        paths: 
            - 'backend/**'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - name: Deploy to Render Web Service
              run: |
                curl "$RENDER_DEPLOY_HOOK_URL"

            env: 
                RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}